name: Doxygen Action

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Ensure this line is correctly added
    - name: Install doxygen
      run: sudo apt-get install -y doxygen

    - name: Install graphviz
      run: sudo apt-get install -y graphviz

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
        
    # Execute mvn doxygen:report to generate the documentation
    - name: Generate Doxygen documentation
      run: |
        cd RouteBusParent
        mvn doxygen:report

    # Deploy the documentation to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: RouteBusParent/target/doxify/html # Directory with generated documentation
