name: Doxygen Action

# Controls when the action will run. Triggers the workflow on push events to the documentation-implementation branch
on:
  push:
    branches: 
      - documentation-implementation

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Ensure this line is correctly added
    - name: Install doxygen
      run: sudo apt-get install -y doxygen

    - name: Install graphviz
      run: sudo apt-get install -y graphviz
    # Set up JDK 11 (or another version if needed)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
        
    # Execute mvn doxygen:report to generate the documentation
    - name: Generate Doxygen documentation
      run: |
      cd RouteBusApp
      mvn doxygen:report

    # Deploy the documentation to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: RouteBusParent/target/doxify/html # Directory with generated documentation
