name: Doxygen Action

# Controls when the action will run. Triggers the workflow on push events to the documentation-implementation branch
on:
  push:
    branches: 
      - documentation-implementation

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v2

    # Run the Doxygen Action to generate documentation
    - name: Generate Doxygen documentation
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        doxyfile-path: "./Doxyfile" # Path to Doxyfile within the RouteBusParent directory
        working-directory: "RouteBusParent" # Working directory where the Doxyfile is located
    
    # Deploy the documentation to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: RouteBusParent/target/doxygen/html # Directory with generated documentation
